baseURL = 'https://blog.xen0n.name/'
title = 'write(2)'
theme = 'PaperMod'

enableEmoji = true

# languages
hasCJKLanguage = true
languageCode = 'zh-cmn-hans-cn'
defaultContentLanguage = 'zh-cmn-hans-cn'

# for raw tags like <sub> to work
[markup.goldmark.renderer]
unsafe = true

# output format
[outputs]
home = ['HTML', 'RSS']

# languages (cont.)
[languages]
[languages.zh-cmn-hans-cn]
languageName = ':cn:'
weight = 1
copyright = 'WANG Xuerui; 以 [cc-by-nc-sa 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans) 授权'
[languages.en]
languageName = ':us:'
weight = 2
copyright = 'WANG Xuerui; licensed with [cc-by-nc-sa 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)'

# menu
[[languages.zh-cmn-hans-cn.menu.main]]
name = '所有文章'
url = 'archives'
weight = 1
[[languages.zh-cmn-hans-cn.menu.main]]
name = '文章类别'
url = '文章类别'
weight = 2

[[languages.en.menu.main]]
name = 'Archive'
url = 'archives'
weight = 1
[[languages.en.menu.main]]
name = 'Categories'
url = 'categories'
weight = 2

# taxonomy
[languages.zh-cmn-hans-cn.taxonomies]
"文章类别" = "文章类别"

[languages.en.taxonomies]
category = "categories"

# theme
[params]
env = 'production'
title = 'write(2)'
keywords = ['blog', 'xen0n']
author = ['WÁNG "xen0n" Xuěruì']
displayFullLangName = true
comments = true

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true

# customized params
icpBeian = '苏ICP备17027553号-1'

[[params.socialIcons]]
name = 'GitHub'
url = 'https://github.com/xen0n'
[[params.socialIcons]]
name = 'GitLab'
url = 'https://gitlab.com/xen0n'
[[params.socialIcons]]
name = 'Bilibili'
url = 'https://space.bilibili.com/192484'
[[params.socialIcons]]
name = 'NeteaseCloudMusic'
url = 'https://music.163.com/#/user/home?id=79360463'
[[params.socialIcons]]
name = 'PGPKey'
url = 'https://keyserver.ubuntu.com/pks/lookup?search=0xc01f7214bc931414&fingerprint=on&op=index'
[[params.socialIcons]]
name = 'RSS'
url = 'index.xml'

[languages.zh-cmn-hans-cn.params]
languageAltTitle = '简体中文（大陆普通话）'
description = '漫步匠人的只言片语'
DateFormat = '2006/01/02'

[languages.zh-cmn-hans-cn.params.homeInfoParams]
Title = 'write(2)'
Content = """
漫步匠人的只言片语。
"""

[languages.en.params]
languageAltTitle = 'English (US)'
description = 'random thoughts from the wandering craftsman'

[languages.en.params.homeInfoParams]
Title = 'write(2)'
Content = """
Random thoughts from the wandering craftsman.
"""

# nitty-gritty details
[module]

[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['**/*.d']
