#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import pathlib

THIS_DIR = pathlib.Path(__file__).parent
PYBBLE_PATH = THIS_DIR / '_generator'
sys.path.insert(0, str(PYBBLE_PATH.resolve()))

from pybble.cli import main


if __name__ == '__main__':
    sys.exit(main())


# vim:set ai et ts=4 sw=4 sts=4 fenc=utf-8:
